/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tareaprogra3;

import clases.pacientes2;
import clases.postgreeconexion;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anaca
 */
public class editpacientes extends javax.swing.JFrame {

    /**
     * Creates new form editpacientes
     */
    verpacientes pacien = new verpacientes();
    pacientes2 verpacin = new pacientes2();
    
    public editpacientes() throws SQLException {
        initComponents();
        mostrardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        npaciente1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dpi1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fecha1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lugar1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        alergias1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sexo1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telefono1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hingreso1 = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        atras1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Actualizar Pacientes");

        jLabel2.setText("No. Paciente");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("DPI");

        dpi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpi1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha De Nacimiento");

        fecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Lugar de Residencia ");

        jLabel8.setText("Alergias");

        jLabel9.setText("Sexo");

        jLabel10.setText("Telefono");

        jLabel11.setText("Hora ingreso");

        modificar.setText("Guardar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        atras1.setText("Atras");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(fondoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(npaciente1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(nombre1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(fondoLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabel3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel7)))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)))
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                                        .addComponent(atras1)
                                        .addGap(18, 18, 18)
                                        .addComponent(eliminar)
                                        .addGap(22, 22, 22)
                                        .addComponent(modificar))
                                    .addGroup(fondoLayout.createSequentialGroup()
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fondoLayout.createSequentialGroup()
                                                    .addGap(40, 40, 40)
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(fondoLayout.createSequentialGroup()
                                                            .addGap(45, 45, 45)
                                                            .addComponent(jLabel9))
                                                        .addComponent(telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(alergias1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(dpi1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hingreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel8)
                                .addGap(120, 120, 120)
                                .addComponent(jLabel10)
                                .addGap(99, 99, 99)
                                .addComponent(jLabel11)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(64, 64, 64))))
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lugar1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npaciente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(84, 84, 84)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lugar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alergias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hingreso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminar)
                    .addComponent(modificar)
                    .addComponent(atras1))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha1ActionPerformed

    private void mostrardatos() throws SQLException{
        npaciente1.setEditable(false);
        
        npaciente1.setText(verpacin.getNopaciente1());
        nombre1.setText(verpacin.getNombre1());
        apellido1.setText(verpacin.getApellido1());
        sexo1.setText(verpacin.getSexo1());
        fecha1.setText(verpacin.getFecha1());
        dpi1.setText(verpacin.getDpi1());
        lugar1.setText(verpacin.getLugar1());
        alergias1.setText(verpacin.getAlergias1());
        telefono1.setText(verpacin.getTelefono1());
        hingreso1.setText(verpacin.getHoraingreso1());
        
        
        
    }
    
    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:

        verpacin.setNopaciente1(npaciente1.getText());
        verpacin.setNombre1(nombre1.getText());
        verpacin.setApellido1(apellido1.getText());
        verpacin.setSexo1(sexo1.getText());
        verpacin.setFecha1(fecha1.getText());
        verpacin.setDpi1(dpi1.getText());
        verpacin.setLugar1(lugar1.getText());
        verpacin.setAlergias1(alergias1.getText());
        verpacin.setTelefono1(telefono1.getText());
        verpacin.setHoraingreso1(hingreso1.getText());
        
        actualizar1(verpacin.getNopaciente1(), verpacin.getNombre1(), verpacin.getApellido1(), verpacin.getSexo1(), 
                verpacin.getFecha1(), verpacin.getDpi1(), verpacin.getLugar1(), verpacin.getAlergias1(), verpacin.getTelefono1(), verpacin.getHoraingreso1());
        
        verpacientes pacint = new verpacientes();
        pacint.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_modificarActionPerformed

    private void actualizar1(String nopaciente, String nombre, String apellido, String sexo,
    String fecha, String dpi, String lugar, String alergias, String telefono, String horaingreso){
     
        try {
             postgreeconexion conexion = new postgreeconexion();
            Connection CONEXION = conexion.connectarPostgree();
             Statement statement;
            statement = CONEXION.createStatement(); 
           String SQL = "UPDATE public.pacientez "+
                   "set nombre = '"+nombre+"', apellido = '"+apellido+"', sexo = '"+sexo+"', fecha = '"+fecha+"'," +
                   "dpi = '"+dpi+"', lugar = '"+lugar+"', alergias = '"+alergias+"', telefono = '"+telefono+"', hora_ingreso = '"+horaingreso+"'";
        statement.executeUpdate(SQL);
             CONEXION.close();//SIEMPRE SE CIERRA LA CONEXION
            CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
            conexion = null;
          JOptionPane.showMessageDialog(null,"el registro se actualizo", "Exito", JOptionPane.INFORMATION_MESSAGE);
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error al actualizar"+e, "Error", JOptionPane.ERROR_MESSAGE);
        }    }
    
    private void dpi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpi1ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        
        verpacin.setNopaciente1(npaciente1.getText());
        eliminar(verpacin.getNopaciente1());
        verpacientes pacint = new verpacientes();
        pacint.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_eliminarActionPerformed

     private void eliminar(String nopaciente ){
        try {
            
             postgreeconexion conexion = new postgreeconexion();
            Connection CONEXION = conexion.connectarPostgree();
             Statement statement;

            statement = CONEXION.createStatement(); 
            
            String SQL = "DELETE FROM public.pacientez WHERE nopaciente = '"+nopaciente+"'; ";
            statement.executeUpdate(SQL);
            CONEXION.close();//SIEMPRE SE CIERRA LA CONEXION
            CONEXION = null; // SE COLOCA A NULL LA CONEXION PARA QUE EL GC TOME ESTE OBJETO Y LO ELIMINE DE MEMORIA
            conexion = null;
            JOptionPane.showMessageDialog(null,"el registro eliminado correctamente", "Eliminado", JOptionPane.INFORMATION_MESSAGE);
 
            
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null,"Error al eliminar el registro"+e, "Error", JOptionPane.ERROR_MESSAGE);

        }
   
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editpacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editpacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editpacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editpacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new editpacientes().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(editpacientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alergias1;
    private javax.swing.JTextField apellido1;
    private javax.swing.JButton atras1;
    private javax.swing.JTextField dpi1;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha1;
    private javax.swing.JPanel fondo;
    private javax.swing.JTextField hingreso1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lugar1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField npaciente1;
    private javax.swing.JTextField sexo1;
    private javax.swing.JTextField telefono1;
    // End of variables declaration//GEN-END:variables
}
